### ISSUE TITLE
（经典loser样例）此人人品有严重问题，忘周知 

### ISSUE THREAD

**Issue by yehx1** [luo-zi/luo-zi.github.io#1]
此人人品有严重问题，忘周知

**Comment by yehx1** [comment]
请参考[https://github.com/Long-Ni/CampusInfo/issues](url)

**Comment by luo-zi** [comment]
> 请参考[https://github.com/Long-Ni/CampusInfo/issues](url)
给我整笑了，我要把你这个issue挂在最顶上，让我的学生们来慢慢观赏哈哈哈
居然有人觉得喝开源血还骂别人忘本是一种占理的行为
你干的事情将被挂在耻辱柱上

**Comment by luo-zi** [comment]
开仓库完全不放内容只作引流
就是完全有悖开源道德的做法，污染开源仓库的环境
别说大家冤枉你，github不是csdn，开源道德也绝不是你想忽视就能忽视
